# fly.toml app configuration file generated for blade-personal on 2023-07-04T14:07:25-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "blade-personal"
primary_region = "iad"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
